import { autoGeneratedImages } from './catalogData';
import { autoGeneratedImages2 } from './catalogData2';
import { autoGeneratedImages3 } from './catalogData3';
import { autoGeneratedImages4 } from './catalogData4';
import { autoGeneratedImages5 } from './catalogData5';
import { autoGeneratedImages6 } from './catalogData6';
import { autoGeneratedImages7 } from './catalogData7';
import { autoGeneratedImages8 } from './catalogData8';
import { autoGeneratedImages9 } from './catalogData9';
import { autoGeneratedImages10 } from './catalogData10';
import { autoGeneratedImages11 } from './catalogData11';
import { autoGeneratedImages12 } from './catalogData12';
import { autoGeneratedImages13 } from './catalogData13';
import { autoGeneratedImages14 } from './catalogData14';
import { autoGeneratedImages15 } from './catalogData15';
import { autoGeneratedImages16 } from './catalogData16';
import { autoGeneratedImages17 } from './catalogData17';
import { autoGeneratedImages18 } from './catalogData18';
import { autoGeneratedImages19 } from './catalogData19';
import { autoGeneratedImages20 } from './catalogData20';
import { autoGeneratedImages21 } from './catalogData21';
import { autoGeneratedImages22 } from './catalogData22';
import { autoGeneratedImages23 } from './catalogData23';
import { autoGeneratedImages24 } from './catalogData24';
import { autoGeneratedImages25 } from './catalogData25';
import { autoGeneratedImages26 } from './catalogData26';
import { autoGeneratedImages27 } from './catalogData27';
import { autoGeneratedImages28 } from './catalogData28';
import { autoGeneratedImages29 } from './catalogData29';
import { autoGeneratedImages30 } from './catalogData30';
import { autoGeneratedImages31 } from './catalogData31';
import { autoGeneratedImages32 } from './catalogData32';
import { autoGeneratedImages33 } from './catalogData33';
import { autoGeneratedImages34 } from './catalogData34';
import { autoGeneratedImages35 } from './catalogData35';
import { autoGeneratedImages36 } from './catalogData36';

export const catalogImages = [
  ...autoGeneratedImages,
  ...autoGeneratedImages2,
  ...autoGeneratedImages3,
  ...autoGeneratedImages4,
  ...autoGeneratedImages5,
  ...autoGeneratedImages6,
  ...autoGeneratedImages7,
  ...autoGeneratedImages8,
  ...autoGeneratedImages9,
  ...autoGeneratedImages10,
  ...autoGeneratedImages11,
  ...autoGeneratedImages12,
  ...autoGeneratedImages13,
  ...autoGeneratedImages14,
  ...autoGeneratedImages15,
  ...autoGeneratedImages16,
  ...autoGeneratedImages17,
  ...autoGeneratedImages18,
  ...autoGeneratedImages19,
  ...autoGeneratedImages20,
  ...autoGeneratedImages21,
  ...autoGeneratedImages22,
  ...autoGeneratedImages23,
  ...autoGeneratedImages24,
  ...autoGeneratedImages25,
  ...autoGeneratedImages26,
  ...autoGeneratedImages27,
  ...autoGeneratedImages28,
  ...autoGeneratedImages29,
  ...autoGeneratedImages30,
  ...autoGeneratedImages31,
  ...autoGeneratedImages32,
  ...autoGeneratedImages33,
  ...autoGeneratedImages34,
  ...autoGeneratedImages35,
  ...autoGeneratedImages36,
];
